;; -*- coding: utf-8-unix; mode: Emacs-Lisp -*-
;; my-keymap-undefined.el
;; ----------------------------------------------------------------------
;; * [2012-02-09 木] global-map で空いている keybind を表示する。
;; TODO terminal で使用可能か否かを表示する。
(defun my-undefined-key-in-global-map ()
  "global-map で空いている keybind を表示する。"
  (interactive)
  (progn
    (message "C-h C-j")
    (message "C-h C-k")
    (message "C-h C-l")
    (message "C-h C-q")
    (message "C-h C-r")
    (message "C-h C-u")
    (message "C-h C-v")
    (message "C-h C-y")
    (message "C-h C-z")
    (message "上記以外の C-h C-<alpha> は定義済み。")
    (message "M-+")
    (message "C-M-g")
    (message "C-M-z")
    (message "<C-M-backspace>")
    (message "C-z C-z")
    (message "<C-M-attn>")
    (message "C-z C-j")
    (message "C-x C-,")
    (message "C-c C-,")
    (message "M-+")
    (message "C-M-,")
    (message "C-x ?")
    (message "C-z ?")
    (message "? は使わない方がいい？ http://ergoemacs.org/emacs/keyboard_shortcuts.html The question mark ? or any combination with it. (due to emacs technical implementation quirk)")
    (message "C-M-j")
    (message (kbd "M-j"))
    (message "indent-new-comment-line C-M-j M-j 片方は要らない。")
    (switch-to-buffer-other-window "*Messages*")
    (end-of-buffer nil)
    )
  )
